-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 23:20:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema comidassql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `comidassql` ;

-- -----------------------------------------------------
-- Schema comidassql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `comidassql` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `comidassql` ;

-- -----------------------------------------------------
-- Table `comidassql`.`restaurante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`restaurante` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`restaurante` (
  `Restaurante_ID` INT NOT NULL,
  `Resyaurante_Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Direccion` VARCHAR(50) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Restaurante_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comidassql`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`menu` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`menu` (
  `Menu_ID` INT NOT NULL,
  `Personalizable` TINYINT(1) NULL DEFAULT NULL,
  `Nombre_Menu` VARCHAR(50) NULL DEFAULT NULL,
  `Restaurante_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Menu_ID`),
  CONSTRAINT `FK_Menu_Restaurante`
    FOREIGN KEY (`Restaurante_ID`)
    REFERENCES `comidassql`.`restaurante` (`Restaurante_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `IXFK_Menu_Restaurante` ON `comidassql`.`menu` (`Restaurante_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `comidassql`.`comida_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`comida_item` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`comida_item` (
  `Comida_ID` INT NOT NULL,
  `Comida_Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Cantidad_Stock` INT NULL DEFAULT NULL,
  `Precio` INT NULL DEFAULT NULL,
  `Menu_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Comida_ID`),
  CONSTRAINT `FK_Comida_Item_Menu`
    FOREIGN KEY (`Menu_ID`)
    REFERENCES `comidassql`.`menu` (`Menu_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `IXFK_Comida_Item_Menu` ON `comidassql`.`comida_item` (`Menu_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `comidassql`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`ingredientes` (
  `Ingrediente_ID` INT NOT NULL,
  `Ingrediente_Nombre` VARCHAR(50) NULL DEFAULT NULL,
  `Stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Ingrediente_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comidassql`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`usuario` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`usuario` (
  `Usuario_ID` INT AUTO_INCREMENT NOT NULL,
  `Usuario_Nombre` VARCHAR(50) NOT NULL,
  `Usuario_Direccion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Usuario_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `comidassql`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`orden` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`orden` (
  `Orden_ID` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio_Unidad` INT NOT NULL,
  `Sub_Total` INT NOT NULL,
  `Fecha_Orden` DATE NULL DEFAULT NULL,
  `Usuario_ID` INT NULL DEFAULT NULL,
  `comida_item_Comida_ID` INT NOT NULL,
  PRIMARY KEY (`Orden_ID`),
  CONSTRAINT `fk_orden_comida_item1`
    FOREIGN KEY (`comida_item_Comida_ID`)
    REFERENCES `comidassql`.`comida_item` (`Comida_ID`),
  CONSTRAINT `FK_Orden_Usuario`
    FOREIGN KEY (`Usuario_ID`)
    REFERENCES `comidassql`.`usuario` (`Usuario_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `IXFK_Orden_Usuario` ON `comidassql`.`orden` (`Usuario_ID` ASC) VISIBLE;

CREATE INDEX `fk_orden_comida_item1_idx` ON `comidassql`.`orden` (`comida_item_Comida_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `comidassql`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`pagos` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`pagos` (
  `Pagos_ID` INT NOT NULL,
  `Pago_Fecha` DATE NULL DEFAULT NULL,
  `Pago_Monto` INT NULL DEFAULT NULL,
  `Orden_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Pagos_ID`),
  CONSTRAINT `FK_Pagos_Orden`
    FOREIGN KEY (`Orden_ID`)
    REFERENCES `comidassql`.`orden` (`Orden_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `IXFK_Pagos_Orden` ON `comidassql`.`pagos` (`Orden_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `comidassql`.`comida_item_has_ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comidassql`.`comida_item_has_ingredientes` ;

CREATE TABLE IF NOT EXISTS `comidassql`.`comida_item_has_ingredientes` (
  `comida_item_Comida_ID` INT NOT NULL,
  `ingredientes_Ingrediente_ID` INT NOT NULL,
  PRIMARY KEY (`comida_item_Comida_ID`, `ingredientes_Ingrediente_ID`),
  CONSTRAINT `fk_comida_item_has_ingredientes_comida_item1`
    FOREIGN KEY (`comida_item_Comida_ID`)
    REFERENCES `comidassql`.`comida_item` (`Comida_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comida_item_has_ingredientes_ingredientes1`
    FOREIGN KEY (`ingredientes_Ingrediente_ID`)
    REFERENCES `comidassql`.`ingredientes` (`Ingrediente_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_comida_item_has_ingredientes_ingredientes1_idx` ON `comidassql`.`comida_item_has_ingredientes` (`ingredientes_Ingrediente_ID` ASC) VISIBLE;

CREATE INDEX `fk_comida_item_has_ingredientes_comida_item1_idx` ON `comidassql`.`comida_item_has_ingredientes` (`comida_item_Comida_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
